Ot89 404 endpoint eliminarusuario server
alkemyTech/OT-89-server pull request #15
Opened 2021-11-05 14:50 UTC by ilqcho

SUMMARY:

.Added validation for user soft delete endpoint
.Updated and fixed the status of user endpoints

PD: Ya había creado el endpoint para el soft delete de usuario en el ticker "screenMiPerfil-server"

2021-11-05 15:40 UTC, nepha199 approved these changes
En ningún momento estas validando que el usuario este logeado ni que tenga credenciales correctas.
Igualmente seria trabajo de un middleware de autenticación.

2021-11-05 15:40 UTC, nepha199 commented on routes/users.js
> +    const { firstName, lastName, email } = await User.findOne({
podes hacer
`User.findByPk(req.params.id)`

2021-11-05 16:10 UTC, MarcosCaballero requested changes

2021-11-05 16:10 UTC, MarcosCaballero commented on routes/users.js
> +      throw new Error(
Este mensaje tendrias que mandarcelo al front a travez de un res.json(message: mensaje)
Este throq error solo se muestra en la consola

2021-11-05 16:18 UTC, nepha199 commented on routes/users.js
> +      throw new Error(
no, fijate q al final de app.js hay un error handler que permite nuclear el manejo de estos `throw new Error("...")` y envia una respuesta medio estandar/dinamica segun lo que le llega

2021-11-05 17:27 UTC, MarcosCaballero approved these changes

2021-11-06 18:38 UTC, bvonpotobsky approved these changes
Buen trabajo Igna!

2021-11-06 18:38 UTC, bvonpotobsky commented on routes/users.js
> +    const { firstName, lastName, email } = await User.findOne({
Muy buena implementación Igna, el único comentario que agregaría es el mismo que Martín.

2021-11-07 23:43 UTC, luciano393 approved these changes

2021-11-07 23:43 UTC, merged