OT89-431 Crear migración y modelo de Contactos
alkemyTech/OT-89-server pull request #22
Opened 2021-11-09 23:16 UTC by MarcosCaballero

COMO: Usuario administrador
QUIERO: Almacenar los datos al completar el formulario de contacto
PARA: Tener una base de datos de contactos

Criterios de aceptación: Al completar el formulario de contacto, se almacenará en la base de datos. Nombre de tabla: contacts. Contendrá los campos name, phone, email, message, deletedAt (utilizada para soft delete)

2021-11-09 23:16 UTC, coltking approved these changes
una maravilla martinez

2021-11-10 21:45 UTC, bvonpotobsky commented
Excelente Marcos.

2021-11-10 21:45 UTC, ilqcho approved these changes

2021-11-10 21:46 UTC, bvonpotobsky approved these changes

2021-11-10 23:44 UTC, luciano393 approved these changes
Me gusta tu estilo

2021-11-11 21:13 UTC, nepha199 requested changes
Saca (o comproba que funciona tal cual) el stringValidator de models/contact.js

2021-11-11 21:13 UTC, nepha199 commented on models/contact.js
> +      },
Saca el stringValidation porque va a rebotar las `@`
Con isEmail alcanza

2021-11-11 21:13 UTC, nepha199 commented on routes/users.js
> +        response ? res.json({data: req.body }) : res.json({ response })
Este y en la linea  38 no se entiende que hacen...

2021-11-11 21:13 UTC, nepha199 commented on routes/users.js
> +            firstName: req.body.firstName,
este if lo podrías haber usado para definir un payload que le pases al update, y entonces el update y la respuesta la escribías una sola vez
El payload lo habrías definido con la misma lógica que diferenciaste un update del otro

2021-11-12 15:52 UTC, nepha199 commented on models/contact.js
> +      },
@MarcosCaballero

2021-11-12 16:14 UTC, MarcosCaballero commented on models/contact.js
> +      },
Dale martin ahora llego a casa y realizo los cambios correspondientes. Muchas gracias

2021-11-12 18:17 UTC, ilqcho approved these changes

2021-11-13 19:46 UTC, Chamarez approved these changes

2021-11-14 20:13 UTC, nepha199 commented on models/contact.js
> +          },
el "Invalid email" no era un mensaje de error general, sino puntualmente del StringValidation. Ahora te quedo una estructura incompleta para la validación custom que representa el `is:{}`. No se si ira a generar un error

2021-11-15 13:24 UTC, mframirezfuentes approved these changes

2021-11-15 19:33 UTC, merged