Route and controller Update Novelities
alkemyTech/OT-89-server pull request #25
Opened 2021-11-11 00:29 UTC by mframirezfuentes

COMO: Usuario administrador
QUIERO: Actualizar una novedad existente
PARA: Mantener el contenido actualizado

Criterios de aceptación: PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados.

Change to NewsController and news router

2021-11-11 18:35 UTC, ilqcho approved these changes

2021-11-11 18:47 UTC, ilqcho commented on controllers/NewsController.js
> +    res.send(update)
Aca tambien, deberia ser res.json

2021-11-11 18:48 UTC, ilqcho approved these changes

2021-11-11 21:22 UTC, nepha199 requested changes
Casi que hasta te debo que te lo arregle yo xD

2021-11-11 21:22 UTC, nepha199 commented on controllers/NewsController.js
> +    res.status(200).json({message:"Actualizado de forma correcta",data:update});
Se que te dije que iba a funcionar, no me acuerdo xq estaba seguro que si.
Pero hoy lo estuve testeando para mi ticket, y termine encontrando en la documentación que solo te devuelve la entrada modificada en Postgres.
Necesitarías hacer un findbypk y devolver eso

[documentacion](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-update)
> options.returning : If true, append RETURNING <model columns> to get back all defined values; if an array of column names, append RETURNING <columns> to get back specific columns (Postgres only)

2021-11-12 00:53 UTC, coltking approved these changes

2021-11-12 02:13 UTC, nepha199 approved these changes

2021-11-12 02:13 UTC, nepha199 commented on controllers/NewsController.js
> +        })
ya comprobaste arriba q exista el id

2021-11-15 16:48 UTC, coltking reviewed
busca que exista el item 2 veces en la db

2021-11-17 15:05 UTC, nepha199 requested changes
lo importante a corregir es el `routes/news.js `

2021-11-17 15:05 UTC, nepha199 commented on controllers/NewsController.js
> +          data: update
deberías devolver `noveletyUpdate` xq `update` va a ser un array con el nro de noseque afectados... o no devolver data

2021-11-17 15:05 UTC, nepha199 commented on routes/news.js
> +router.route("/news/:id").put(NewsUpdate)
> COMO: Usuario administrador

no estas validando q lo sea y tenes q quitarle el `/news` xq ya esta especificado en el `app.js` , asi la ruta te quedaria `/news/news/:id`

`router.route("/:id").put(IsAuthenticated, IsAdmin, NewsUpdate)`

2021-11-17 15:31 UTC, nepha199 approved these changes

2021-11-19 17:33 UTC, merged