Endpoint creacion testimonios
alkemyTech/OT-89-server pull request #39
Opened 2021-11-16 13:21 UTC by coltking

COMO usuario administrador
QUIERO dar de alta nuevos testimonios
PARA informar novedades acerca de la ONG.

Criterios de aceptación:POST /testimonials - Deberá validar la existencia de los campos name y content enviados, para almacenar el registro en la tabla testimonials.

2021-11-17 00:09 UTC, MarcosCaballero requested changes
todo mal flaco, crear no eliminar.

2021-11-17 00:17 UTC, MarcosCaballero approved these changes
Bien los cambios requeridos.

2021-11-17 15:20 UTC, nepha199 requested changes

2021-11-17 15:20 UTC, m-cappi commented on routes/testimonials.js
> +        Testimonials.create({
> COMO usuario administrador

valida el usuario guachin

2021-11-17 15:25 UTC, nepha199 approved these changes

2021-11-19 13:40 UTC, mframirezfuentes approved these changes

2021-11-19 17:22 UTC, merged