Enpoint para almacenar contactos
alkemyTech/OT-89-server pull request #40
Opened 2021-11-16 13:58 UTC by mframirezfuentes

COMO: Desarrollador
QUIERO: Enviar los datos del formulario de contacto a la API 
PARA: Almacenarlos en la base de datos

Criterios de aceptación: POST /contacts - Verificará que la petición contenga los campos name y email

2021-11-16 21:02 UTC, ilqcho commented on controllers/ContactsController.js
> +  if(!name && !email){
Aca deberia ser || en vez de &&

2021-11-16 21:06 UTC, ilqcho approved these changes

2021-11-17 14:03 UTC, coltking requested changes

2021-11-17 14:03 UTC, coltking commented on controllers/ContactsController.js
> +  if(!name && !email){
^

2021-11-17 15:29 UTC, nepha199 requested changes
- corregi `routes/contacts.js`
- y fijate el comentario de Igna, que en ese if entrarias solo si te faltan **ambos** campos

2021-11-17 15:29 UTC, nepha199 commented on routes/contacts.js
> +router.route("/contacts").post(IsAuthenticated, IsAdmin,StoreContact)
`route("/contacts")` generaria una ruta `/contacts/contacts` xq ya tenes un `/contacts `consumido a nivel de `app.js`.
Dejalo como `route("/")`

2021-11-18 00:45 UTC, nepha199 approved these changes

2021-11-18 14:46 UTC, Chamarez approved these changes

2021-11-18 14:54 UTC, merged