First commit model created, endpoint modified
alkemyTech/OT-89-server pull request #46
Opened 2021-11-17 15:56 UTC by Chamarez

COMO usuario
QUIERO ver los links de las redes sociales al entrar a la página
PARA poder acceder a ellas.

Criterios de aceptación:

Al devolver los datos en el endpoint de datos públicos, agregar los campos de redes sociales en la respuesta

2021-11-17 16:18 UTC, coltking commented on routes/organizations.js
> +const Organizations = require('../models/organization')
Aca yo tube problemas al importar asi los modelos, lo solucione importandolo de esta manera:
const db = require('../models/index')
const Testimonials = db.sequelize.models.testimonials;

2021-11-17 16:25 UTC, coltking requested changes

2021-11-17 16:25 UTC, coltking commented on models/organization.js
> +'use strict';
Hay que eliminar este archivo que lo hizo luciano que tenia el ticket

2021-11-17 16:25 UTC, MarcosCaballero requested changes
Mepa trepa que estas haciendo algo que no va en tu ticket. El model de organization no va.

2021-11-17 17:02 UTC, m-cappi commented on routes/organizations.js
>      })
- el PK de tu modelo es `id`, no `organizationId`. Podes fijarte en el archivo de migrations
- findAll te va a devolver un array y va a fallar la desestructuracion. Usa findByPk o findOne

2021-11-17 18:20 UTC, ilqcho commented on routes/organizations.js
>  router.get('/:id/public', async (req, res, next) => {
Creo que el id en la ruta no deberia estar

2021-11-17 20:06 UTC, ilqcho commented on routes/organizations.js
> +    res.send({name, image, phone, address, welcomeText, instagram, facebook})
res.json en vez de res.send

2021-11-19 14:46 UTC, coltking approved these changes

2021-11-19 17:25 UTC, merged