first commit with put endpoint
alkemyTech/OT-89-server pull request #47
Opened 2021-11-17 16:24 UTC by Chamarez

COMO usuario administrador
QUIERO modificar una categoría existente
PARA mantener la información actualizada

Criterios de aceptación:
PUT /categories/:id - Deberá validar que la categoría existe y actualizarla, caso contrario devolver un error

2021-11-17 17:06 UTC, nepha199 requested changes

2021-11-17 17:06 UTC, nepha199 commented on controllers/CategoryController.js
> +  res.status(201).json("Operation Modified");
`jason()` no te obliga a que sea un objeto tipo json? no te salta error mandando un string solo?

2021-11-17 17:06 UTC, nepha199 commented on services/categoryService
> +const categories = db.sequelize.models.categories;
- al archivo le falto la extension .js, por eso parece una archivo de texto
- tenes que respetar las mayusculas o no te lo va a tomar y te sobro el sequelize, `db.models.Categories`

2021-11-17 18:30 UTC, Chamarez commented on controllers/CategoryController.js
> +  res.status(201).json("Operation Modified");
Nop, funciona bien asi

2021-11-17 18:31 UTC, Chamarez commented on services/categoryService
> +const categories = db.sequelize.models.categories;
Genial, no me di cuenta en breve lo arreglo, gracias

2021-11-18 00:48 UTC, nepha199 approved these changes

2021-11-18 02:38 UTC, ilqcho approved these changes

2021-11-19 14:43 UTC, coltking approved these changes
A los amigos todo, a los enemigos ni justicia

2021-11-19 17:23 UTC, merged